import Head from 'next/head';

const Blog = () => {
  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>This is the blog</h1>
    </div>
  );
};

export default Blog;
